### ISSUE TITLE
Minimum Lua version?

### ISSUE THREAD

**Issue by lmartinez-mirror** [Rosettea/Lunacolors#1]
Hi, package maintainer for Hilbish here. With release 0.4.0, I've decided to package Lunacolors for the AUR instead of tying it to Hilbish. The source tarball doesn't come with the git info anyways, so I'd have no way of pulling this.

I only need to know if this library targets a specific Lua version to decide whether I need to split this package or not.

**Comment by sammy-ette** [comment]
ill say the minimum version that works is 5.1, since [gopher-lua](https://github.com/yuin/gopher-lua) (the lua vm for Hilbish) is 5.1
